# Site settings
title: Hemant Kumar's CV 
description: Hemant Kumars CV
favicon: /assets/img/hemant.png
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Hemant Kumar
  title: Java Developer and Architect
  address: Columbus, Ohio
  email: techhb@gmail.com
  link: https://hemantkumar.tk
  weibo:
  github: techhb
  linkedin: hemantkumar98
  twitter: 
  gavatar: /resumecard/assets/img/hemant.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Punjabi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Spring Boot
      percentage: 90%
    - skill2:
      name: Java 8
      percentage: 80%
    - skill3:
      name: Cassandra
      percentage: 70%
    - skill4:
      name: SQL
      percentage: 70%
    - skill5:
      name: Java Testing (Mockito/Cucumber/Junit/TestNg)
      percentage: 90%
    - skill6:
      name: Cloud Development
      percentage: 60%
