# Site settings
title: Hemant Kumar's CV 
description: Hemant Kumars CV
favicon: /assets/img/hemant.png
baseurl: https://techhb.github.io/hemant-resume
url: https://techhb.github.io/hemant-resume
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Hemant Kumar
  title: Java Developer and Architect
  address: Columbus, Ohio
  email: techhb@gmail.com
  profileSummary: Java Developer/Architect with 13 years of success in conceptualizing technical solutions and system development environments. Focused on working closely with clients to determine technical project objectives, specifications and solutions. Detail-oriented in coding and testing the functionality of deliverable.
  link: https://hemantkumar.tk
  weibo:
  github: techhb
  linkedin: hemantkumar98
  twitter: 
  gavatar: /resumecard/assets/img/hemant.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Polaris Consulting & Services Ltd, Columbus, OH (Client:Chase)
      location: Columbus, OH
      title: Java Developer/Architect
      started: 2018
      duration: (2018,May - Present)
      description: 
        Worked at Chase on Fraud Detection domain to analyze application for potential fraud, by checking requests coming from multiple apps against our risk engine.<br>
        • Collaborated with clients to determine epic/stories specifications and scope.<br>
        • Creating and updating design document for stories.<br>
        • Modified current application to PAAS compatible apps following 12 factor design principles.<br>
        • Implemented various cloud technologies like Resil4j, Config Server, Feign Client in Spring Boot.<br>
        • Controlling application throughput and threading control using Resil4j as well as Hystrix depending upon API choice.<br>
        • Implemented Multithreaded API call to save time using Java Executer Services.<br>
        • Implemented Multithreaded application for multiple daily batch loads related to sensitive data using spring batch as well ThreadPoolExecutor.<br>
        • Implemented Wire-mock mock services on cloud for early development in case API to be consumed are not ready from 3rd party for integration testing.<br>
        • Setting up Kafka Producer and Listeners with Kerberos authentication and SSL with multiple sets of bootstrap servers.<br>
        • Implemented Spring Integration as architectural framework to have better control of application.<br>
        • Implemented Docker Container based implementation for services so that services can be tested based on feature branch by Testing team, reducing the overall release life-cycle.<br>
        • Implemented OAUTH for use by micro services using Spring Boot.<br>
        • Modifying product structures for multiple component reuse across micro services (Code Cleanup).<br>
        • Set Up Coding Guidelines and Continuous involvement in code reviews.<br>
    - work2:
      company: HCL Infosystems Ltd(Client:FedEx)
      location: Orlando, FL
      title: Java Developer/Architect
      started: 2016
      duration: (2016,Nov - 2018,May)
      description: Worked as part of raise team to move existing Rating system to micro-services based PAAS architecture<br>
        •	Worked with business team for stories creation.<br>
        •	Created design document for stories.<br>
        •	Developed new Micro Services workflow for the complete system.<br>
        •	Jenkins build system setup.<br>
        •	Coding for new Stories and maintaining regression.<br>
        •	Setting up cloud config server along with eureka and Hystrix for services.<br>
        •	Spring data JPA Implementation for data storage.<br>
        •	Developed test cases via Mockito and Junit.<br>
        •	Implemented spring JPA integration for DB connectivity.<br>
        •	Performed code reviews and guided team members.<br>

    - work3:
      company: Polaris Consulting and Services Ltd(Client:CitiBank)
      location: Tampa, FL
      title: Senior Java Developer
      started: 2013
      duration: (Feb,2013 - Nov,2016)
      description: Worked Majorly in KYC and Anti Money Laundering Domain.<br>
        •	Modified existing KYC application to correct coding errors, upgrade interfaces and improve overall performance.<br>
        •	Involved in developing code for obtaining Data source, session factory, transaction factory using Spring Dependency injection, access using app context Implementation of DAO, VO for various modules like entitlement module, account profile form module and persistence using Hibernate DAO support API (Hibernate Template).<br>
        •	Wrote and analyzed existing Pl/SQL code of various procedures, functions and corrected the design and performance issues.<br>
        •	Creating ThreadPoolExecutor based services to analyze current load status.<br>
        •	Created Shell Scripts for Scheduled report for frequent user queries along with automation of reports generation and publishing via shell script to senior management.<br>
        •	Performed Query execution improvement using Executor framework and multiple data bases together during Data Loads.<br>
        •	Job status monitoring using AutoSys API Planning and Implementation of COB.<br>
    - work4:
      company: Tech Mahindra, (Client:AT&T)
      location: Richardson, TX and Noida,India
      title: Senior Software Engineer
      started: 2010
      duration: (March,2010 - Feb,2013)
      description: XI is a middle ware which rests between front end systems (System X, OPUS, PDC, Phoenix etc.) and the back-end systems (CSI, ACS etc.).<br>
        •	Wrote highly maintainable, solid code in Java/Spring system that formed core framework and has won consistent praise from subsequent developers since initial version.<br>
        •	Wrote many utilities for further code/test case generation so that further development work is reduced.<br>
        •	Creating and updating coding standard for project.<br>
        •	Developed Systems to Simulate Back-end and created GUI Flow testing utilities using spring, hibernate, JAXB.<br>
        •	Developed test cases via Mockito and Junit.<br>
        •	Made sure that coding is done in Test-driven model to insure least coding issues.<br>
    - work5:
      company: Birlasoft, (Client:AT&T)
      location: Noida,India
      title: Senior Software Engineer
      started: 2009
      duration: (November,2009 - Feb,2010)
      description: Michael Page is One of most recognized Job Portal in UK. Client wanted rebuild of whole system on new system.<br>
        •	Analyzed the requirements and designed the module for Billing and Account.<br>
        •	Low Level Design Document Creation including Class Diagram, Interaction Diagram, Activity Diagram.<br>
        •	Presentation of Proof of Concept for Spring, Hibernate, Drools Integration along with code design with implementation of various pattern.<br>
        •	(SOAP) Web Services Implementation and Configuration in WebLogic for Billing Module.<br>
        •	Created the HLD and LLD, and modelling the application from Requirement.<br>
    - work6:
      company: Amdocs, (Client:Sensis)
      location: Pune,Maharashtra
      title: Senior Subject Matter Expert
      started: 2007
      duration: (Jun,2007 - Apr,2009)
      description: Michael Page is One of most recognized Job Portal in UK. Client wanted rebuild of whole system on new system.<br>
        •	Analyzed the requirements and designed the module for Billing and Account.<br>
        •	Low Level Design Document Creation including Class Diagram, Interaction Diagram, Activity Diagram.<br>
        •	Presentation of Proof of Concept for Spring, Hibernate, Drools Integration along with code design with implementation of various pattern.<br>
        •	(SOAP) Web Services Implementation and Configuration in WebLogic for Billing Module.<br>
        •	Created the HLD and LLD, and modelling the application from Requirement.<br>
    - work7:
      company: JumpGames
      location: Mumbai,Maharashtra
      title: Java Developer
      started: 2007
      duration: (Feb,2007 - Jun,2007)
      description: Ramayana A Mythological Game (4 level side scrolling eye candy) based on Virgin's comic series Ramayana.<br>
        •	Ported Game from BREW(C++) to J2ME.<br>
        •	Modified Current Game Template so that cross platform porting becomes easier.<br>
        •	Developed system to adjust game screen and features according to various device sizes automatically.<br>
    - work8:
      company: Mobera
      location: Chandigarh,India
      title: Software engineer
      started: 2006
      duration: (Feb,2006 - Feb,2007)
      description: Worked on Porting of Pet shop Strategy based Game. The Player has to maintain and sell Pets to the customer, coming frequently player has to play with a well-planned strategy. Game had More than 100 levels.<br>
        •	Setting Build system using Ant.<br>
        •	Ported Game to multiple screen sizes as per devices limitation to make it playable on device that have memory constraints.<br>
  educationHistory:
    - education1:
      organization: Kurukshetra University
      location: Kurukshetra, India
      degree: Masters
      major: Software Engineering
      started: 2003
      duration: (2003 - 2006)
      description: 
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Punjabi
      proficiency: Professional
  certifications:
    - certification1:
      name: DataStax Certified Cassandra Developer Associatite
      url: https://academy.datastax.com/certs/lookup/b9759254-3eba-4d72-882b-a7d694b5aa0a/
    - certification2:
      name: DataStax Certified Cassandra Administrato Associatite
      url: https://academy.datastax.com/certs/lookup/16109304-0f46-4851-b0a6-ce1eeaca17c1/
      url: https://academy.datastax.com/certs/lookup/b9759254-3eba-4d72-882b-a7d694b5aa0a/
    - certification3:
      name: IBM Certified Cloud Application Developer
      url: https://www.youracclaim.com/badges/4d9969c8-72c1-4d99-9e07-e690259a7d3e/linked_in_profile
    - certification4:
      name: Microsoft Certified Azure Fundamentals
      url: https://www.youracclaim.com/badges/f53349fe-85f4-41da-ad2d-d52db8f76d11/linked_in_profile
    - certification5:
      name: Oracle Certified Associate Java 8 Programmer
      url: https://www.youracclaim.com/badges/2d9d6481-48ff-4eb6-b0db-8ce424a8f574/linked_in_profile
    - certification6:
      name: HackerRank Certification in Problem Solving
      url: https://www.hackerrank.com/certificates/58761ec8157e
  programmingSkills:
    - skill1:
      name: Spring Boot
      percentage: 90%
    - skill2:
      name: Java 8
      percentage: 80%
    - skill3:
      name: Cassandra
      percentage: 70%
    - skill4:
      name: SQL
      percentage: 70%
    - skill5:
      name: Java Testing (Mockito/Cucumber/Junit/TestNg)
      percentage: 90%
    - skill6:
      name: Cloud Development(Pivotal/Azure/Kubernetes/Jenkins)
      percentage: 70%
