# Site settings
title: Hemant Kumar's CV 
description: Hemant Kumars CV
favicon: /assets/img/hemant.png
baseurl: https://techhb.github.io/hemant-resume
url: https://techhb.github.io/hemant-resume
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Hemant Kumar
  title: Java Developer and Architect
  address: Columbus, Ohio
  email: techhb@gmail.com
  link: https://hemantkumar.tk
  weibo:
  github: techhb
  linkedin: hemantkumar98
  twitter: 
  gavatar: /resumecard/assets/img/hemant.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Polaris Consulting & Services Ltd, Columbus, OH (Client:Chase)
      location: Columbus, OH
      title: Java Developer/Architect
      started: 2018
      duration: (2018 - Present)
      description: 
        Worked at Chase on Fraud Detection domain to analyze application for potential fraud, by checking requests coming from multiple apps against our risk engine.
       -	Collaborated with clients to determine epic/stories specifications and scope.
       -	Creating and updating design document for stories.
        •	Modified current application to PAAS compatible apps following 12 factor design principles..
        •	Implemented various cloud technologies like Resil4j, Config Server, Feign Client in Spring Boot.
        •	Controlling application throughput and threading control using Resil4j as well as Hystrix depending upon API choice.
        •	Implemented Multithreaded API call to save time using Java Executer Services.
        •	Implemented Multithreaded application for multiple daily batch loads related to sensitive data using spring batch as well ThreadPoolExecutor.
        •	Implemented Wire-mock mock services on cloud for early development in case API to be consumed are not ready from 3rd party for integration testing.
        •	Setting up Kafka Producer and Listeners with Kerberos authentication and SSL with multiple sets of bootstrap servers.
        •	Implemented Spring Integration as architectural framework to have better control of application.
        •	Implemented Docker Container based implementation for services so that services can be tested based on feature branch by Testing team, reducing the overall release life-cycle.
        •	Implemented OAUTH for use by micro services using Spring Boot.
        •	Modifying product structures for multiple component reuse across micro services (Code Cleanup).
        •	Set Up Coding Guidelines and Continuous involvement in code reviews.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Kurukshetra University
      location: Kurukshetra, India
      degree: Masters
      major: Software Engineering
      started: 2003
      duration: (2003 - 2006)
      description: 
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Punjabi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Spring Boot
      percentage: 90%
    - skill2:
      name: Java 8
      percentage: 80%
    - skill3:
      name: Cassandra
      percentage: 70%
    - skill4:
      name: SQL
      percentage: 70%
    - skill5:
      name: Java Testing (Mockito/Cucumber/Junit/TestNg)
      percentage: 90%
    - skill6:
      name: Cloud Development
      percentage: 60%
